### ISSUE TITLE
Can't build following the instructions

### ISSUE THREAD

**Issue by bolatovumar** [breez/breez#104]
I followed all of the steps up to `./build.sh` where it fails. I was trying to tackle https://github.com/breez/breezmobile/issues/242 so I needed to build this first.

I initially got this error: `no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME`. The steps don't mention this `$ANDROID_NDK_HOME` variable so I set it to my NDK path which in my case was `export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/20.1.5948944`.

After setting the env variable above I run `./build.sh` again and I get this error now:

`gomobile: go [list -e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=android,experimental,signrpc,walletrpc,chainrpc,invoicesrpc,routerrpc,backuprpc,peerrpc,submarineswaprpc,breezbackuprpc -- github.com/breez/breez/bindings]: exit status 2: cmd/go: -tags space-separated list contains comma`

Looks like the `tags` parameter above is expected to be space-separated but it's actually comma-separated?

I tried the entire process twice to verify I didn't just skip some steps or something but I get the same error consistently both times.

**OS:** macOS Mojave v10.14.6
**Android SDK:** latest
**Android NDK:** v20.1.5948944
**Go:** go1.12.7 darwin/amd64

Let me know if you require any further details.

**Comment by roeierez** [comment]
@bolatovumar Thanks you very much for your detailed report. It will certainly help us improve the docs.


> The steps don't mention this `$ANDROID_NDK_HOME` variable

See this line in the readme: **_export ANDROID_HOME=\<your android sdk directory\>_**
We assume you installed the ndk as part of your sdk tools then gobind looks for your ndk at this path: $ANDROID_HOME/ndk-bundle. 
I guess in your case it was installed separately and a direct ndk path was required.

> Looks like the `tags` parameter above is expected to be space-separated but it's actually comma-separated?

Actually in build.sh the tags are space separated. I think you get this error because of your go version.

I fixed the documentation based on your report. I was able to build in a clan environment using these steps.
Can you try again and let me know if you are able to build?

**Comment by bolatovumar** [comment]
@roeierez thanks for the updated docs! I was able to build following the updated steps. I now have the `breez-sources.jar` and `breez.aar` files under `build/android` directory.

You are right, I had an older version of Go and that was most likely the issue.

As far as the NDK bit goes, I did install it separately from the SDK tools hence the issue in my case. In my case it wasn't in the `$ANDROID_HOME/ndk-bundle/` directory but in `$ANDROID_HOME/ndk/<ndk-version>` instead.

Closing this issue now.
